
FROM python:3.9

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /app

COPY alembic.ini /app/alembic.ini
COPY alembic /app/alembic

RUN pip install pymongo pydantic[email] psycopg2 authx pendulum python-multipart prometheus-fastapi-instrumentator==5.9.0 python-dotenv

    
EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
